dubbo:
  registry:
    address: spring-cloud://${spring.cloud.nacos.discovery.server-addr}
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.mk.springcloud.dubbo
  cloud:
    subscribed-services: user-provider
#  consumer:
#    check: false

spring:
  application:
    name: class-provider
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 172.0.0.1:8848

server:
  port: 8085

feign:
  hystrix:
    enabled: true

logBack:
  logPathDir: ${logPathDir:./log/${spring.application.name}}
