dubbo:
  registry:
    address: spring-cloud://${spring.cloud.nacos.discovery.server-addr}
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.mk.springcloud.dubbo
  cloud:
    subscribed-services: user-provider,class-provider
#  consumer:
#    check: false

spring:
  application:
    name: dubbo-consumer
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.188:8848

server:
  port: 8086

logBack:
   logPathDir: ${logPathDir:./log/${spring.application.name}}